security:
  user:
    password: ${eureka.password} # Don't use a default password in a real app 
    
server:
  port: 8761
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  password: ${SECURITY_USER_PASSWORD:password}
    
---     
spring:
  profiles: cloud1 # connect to remote peer  

server:
  port: 9898
  
eureka:
  instance:
    hostname: ${VCAP_APP_HOST:test}
  password: ${SECURITY_USER_PASSWORD:password}
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@localhost:8888}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:9899}/eureka/
 
---
spring:
  profiles: cloud2 # connect to remote peer  

server:
  port: 9899
  
eureka:
  instance:
    hostname: ${VCAP_APP_HOST:test}
  password: ${SECURITY_USER_PASSWORD:password}
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@localhost:8888}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:9898}/eureka/
